### ISSUE TITLE
Gradle Dependency does not work

### ISSUE THREAD

**Issue by matthewrice345** [ogaclejapan/ArcLayout#1]
Added:
dependencies {
    ...
    compile 'com.ogaclejapan.arclayout:library:1.0.0@aar' 
}
The library does not get included when synced. Looking at the demo the project was imported not added as a gradle dependency.

**Comment by ogaclejapan** [comment]
Hi @matthewrice345 

Qiitanium Application that use this library do work :)
https://github.com/ogaclejapan/Qiitanium/blob/master/qiitanium/build.gradle

In addition, this library registered with the Maven Central Repository and JCenter Repository.

Maven: 
http://search.maven.org/#artifactdetails%7Ccom.ogaclejapan.arclayout%7Clibrary%7C1.0.0%7Caar

JCenter: 
https://bintray.com/ogaclejapan/maven/ArcLayout/1.0.0/view#files

**Comment by ogaclejapan** [comment]
Hmm, Try to explicitly defined.

```
//build.gradle:

repositories {
    mavenCentral()
    jcenter()
}
```

**Comment by matthewrice345** [comment]
Not sure why it's not downloading the aar for me. I'm including other aar files and they get included. My build.gradle does include maven and jcenter also. The gradle sync completes successfully but none of the classes are available even after a rebuild.

**Comment by ogaclejapan** [comment]
Hi, @matthewrice345 

Did you can download the library?
If you delete the cache of gradle, you may be able to re-download.

http://stackoverflow.com/questions/13565082/how-can-i-force-gradle-to-redownload-dependencies

**Comment by ogaclejapan** [comment]
No reply. close the ticket.
