### ISSUE TITLE
arc_origin="" doesn't work

### ISSUE THREAD

**Issue by Mo7mud** [ogaclejapan/ArcLayout#10]
Hello
sorry for my many questions 
when I imported library into my project using gradle.build dependency it worked fine but it arc is always show centered no matter which value I give in arc_origin 
in demo app it works great but doesn't work in my project I don't know why
thank you very much for your efforts.

I'm trying to use like a path shape.

**Comment by ogaclejapan** [comment]
Can you show me the layout?

**Comment by Mo7mud** [comment]
It worked after removing butternife library from the project I don't what's the conflict between them.
