### ISSUE TITLE
I'm using the library in my app

### ISSUE THREAD

**Issue by Mo7mud** [ogaclejapan/ArcLayout#11]
Hello @ogaclejapan 
Im using your awesome library in my app and here is the link on google play

https://play.google.com/store/apps/details?id=club.androidy.callcontrolfree

 and here is a small screen capture 

https://www.dropbox.com/s/hmsj1oyl8qsjkho/callcontrol.ZIP?dl=0

you can include  this in your documentation.

Thank you very much for your effort.

**Comment by ogaclejapan** [comment]
Hi, @EgyptianM 

Awesome!
Thank you for using my library :+1: 

README has been updated.

**Comment by Mo7mud** [comment]
Hello @ogaclejapan 
This is a lightweight image to use in the documentation 
![callcontro_clip](https://cloud.githubusercontent.com/assets/12565380/12001161/94a14dcc-aaeb-11e5-9144-6bbe40d454bf.gif)

**Comment by ogaclejapan** [comment]
Thank you for lighter.

README Has been updated : )
https://github.com/ogaclejapan/ArcLayout

2015-12-25 16:41 GMT+09:00 Mohammad notifications@github.com:

**Comment by Mo7mud** [comment]
You are welcome!
