### ISSUE TITLE
DefaultMavenFactory error

### ISSUE THREAD

**Issue by figengungor** [ogaclejapan/ArcLayout#6]
I tried to open the project in Android Studio but it gives me this error:

Error:(2, 0) Cause: org/gradle/api/publication/maven/internal/DefaultMavenFactory

Could you please help me out?

**Comment by ogaclejapan** [comment]
Hi, @figengungor 
Thank you for reporting!

Right now, updated the version of the build tool.
I think this problem has been solved :+1:
