### ISSUE TITLE
How to use this library? 

### ISSUE THREAD

**Issue by wensonwang** [ogaclejapan/ArcLayout#7]
Hello,

I am trying to use this library in my project. First I created a new project in Android Studio, and add the following statement into build.gradle: compile 'com.ogaclejapan.arclayout:library:1.0.1@aar'.
but it reported parsing XML error: unbound prefix. And I didn't see the library source code in my project.

Could you give a detailed process to add this library into a new project.

Thanks,
Wilson

**Comment by willqian** [comment]
Hello

Work around -- you can add the library into your project directly

**Comment by vrjgamer** [comment]
i m also not able to add it

**Comment by ogaclejapan** [comment]
> XML error: unbound prefix.

Do you prefix definition?

``` xml
xmlns:app="http://schemas.android.com/apk/res-auto"
```

Original parameters of ArcLayout must be to define the `app:xxxx` prefix

http://stackoverflow.com/questions/2221221/frequent-issues-arising-in-android-view-error-parsing-xml-unbound-prefix
