### ISSUE TITLE
How to make two arcs in same view?

### ISSUE THREAD

**Issue by Mo7mud** [ogaclejapan/ArcLayout#8]
Hello friend
is there any ability to make two arcs in same view?
one inside the other one 
one in left one right
and so on
sorry for my poor English I don't know if I clarified it enough or not.

**Comment by Mo7mud** [comment]
I managed to make it but it only animates and respond to clicks of first set of buttons

![screenshot_2015-12-15-14-57-28](https://cloud.githubusercontent.com/assets/12565380/11811480/6b3c3c08-a33e-11e5-9b04-bf3169b4c474.jpeg)

**Comment by ogaclejapan** [comment]
Hi, @EgyptianM 
Sorry for replying late.

ArcLayout will be only one place either.
But, I think that it can do if you use two of the ArcLayout.

For example

``` java

<FrameLayout>
  <ArcLayout android:layout_gravity="left">
    ... child views
  </ArcLayout>
  <ArcLayout>
    ... child views
  </ArcLayout android:layout_gravity="bottom">
  <FAB/>
</FrameLayout>

```

**Comment by Mo7mud** [comment]
Thank you. I'll try it.
