### ISSUE TITLE
Gradle sync failed: Plugin with id 'com.github.dcendents.android-maven' not found.

### ISSUE THREAD

**Issue by Mo7mud** [ogaclejapan/ArcLayout#9]
HI
I can't import the library as a module into my project
it shows this error

Gradle sync failed: Plugin with id 'com.github.dcendents.android-maven' not found.

**Comment by ogaclejapan** [comment]
Hi, @EgyptianM 

Are you using the dependencies of gradle?
ArcLayout has been published in bintray.
https://bintray.com/ogaclejapan/maven/ArcLayout/view

```
compile "com.ogaclejapan.arclayout:library:1.0.1@aar"
```

If you want to directly import, 'com.github.dcendents.android-maven' plug-in is not required.
I use when uploading the library to bintray.
